### ISSUE TITLE
help

### ISSUE THREAD

**Issue by 0ylz1** [cooldogedev/BuildBattle#2]
When i put this : buildbattle create name game-lobby game-world 30 6 24 300 30 10 10 10 

it’s says - too many arguments given - why?

**Comment by cooldogedev** [comment]
As the command says there's an extra argument being passed, remove the last number (10). The read me has been updated

**Comment by 0ylz1** [comment]
Can you give me your discord please i want private plugin?

**Comment by cooldogedev** [comment]
Doge.#8819
