### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by 0ylz1** [cooldogedev/BuildBattle#3]
THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BuildBattle

Error: cooldogedev\BuildBattle\libs\cooldogedev\libSQL\ConnectionPool::__construct(): Argument #2 ($databaseConfig) must be of type array, bool given, called in phar:///home/minecraft/multicraft/servers/server26525/plugins/BuildBattle.phar/src/cooldogedev/BuildBattle/BuildBattle.php on line 94
File: plugins/BuildBattle.phar/src/cooldogedev/BuildBattle/libs/cooldogedev/libSQL/ConnectionPool
Line: 52

**Comment by cooldogedev** [comment]
corrupted config file
